import React, { createContext, useContext, useEffect, useState } from 'react'

const STORAGE_KEY = 'app-language'

const translations = {
  zh: {
    'common.loading': '加载中...',

    'header.searchPlaceholder': '搜索帖子、用户...',
    'header.toLight': '切换到日间模式',
    'header.toDark': '切换到夜间模式',
    'header.lightLabel': '日间模式',
    'header.darkLabel': '夜间模式',
    'header.create': '发布',
    'header.createTitle': '发布新帖子',
    'header.userMenu': '用户菜单',
    'header.profile': '我的资料',
    'header.logout': '登出',
    'header.login': '登录',
    'header.register': '注册',
    'header.inbox': '通知',
    'header.markAllRead': '全部已读',
    'header.markAsRead': '标记为已读',
    'header.noNotifications': '暂无通知',
    'sidebar.home': '首页',
    'sidebar.about': '关于我们',
    'sidebar.contact': '联系我们',
    'sidebar.changelog': '更新日志',
    'sidebar.fixes': '问题修复',
    'right.categoriesTitle': '版块分类',
    'right.tagsTitle': '标签',
    'right.loading': '加载中...',
    'right.emptyCategories': '暂无版块',
    'right.emptyTags': '暂无标签',
    'right.postsSuffix': '帖子',

    'home.latest': '最新',
    'home.hot': '热门',
    'home.loading': '加载中...',
    'home.emptyTitle': '暂无帖子',
    'home.emptyDesc': '暂时没有找到相关帖子，请稍后再试',
    'home.loadMore': '加载更多',
    'search.title': '搜索结果',
    'search.keywordPrefix': '关键词：',
    'search.loading': '搜索中...',
    'search.enterKeyword': '请输入搜索关键词',
    'search.noResultsTitle': '未找到相关帖子',
    'search.noResultsDesc': '没有找到包含该关键词的帖子，请尝试其他关键词',
    'search.resultsPrefix': '找到',
    'search.resultsSuffix': '个结果',

    'auth.loginTitle': '登录',
    'auth.agreementPrefix': '继续操作即表示您同意我们的',
    'auth.agreementUser': '用户协议',
    'auth.agreementPrivacyPrefix': '并确认您了解',
    'auth.agreementPrivacy': '隐私政策',
    'auth.emailOrUsername': '邮箱或用户名 *',
    'auth.emailOrUsernamePlaceholder': '邮箱或用户名',
    'auth.password': '密码 *',
    'auth.passwordPlaceholder': '密码',
    'auth.forgotPassword': '忘记密码？',
    'auth.loggingIn': '登录中...',
    'auth.login': '登录',
    'auth.newUser': '新用户？',
    'auth.register': '注册',
    'create.title': '发布新帖子',
    'create.fieldTitle': '标题 *',
    'create.fieldCategory': '版块 *',
    'create.fieldContent': '内容 *',
    'create.fieldTags': '标签（可选）',
    'create.placeholderTitle': '请输入帖子标题（5-200个字符）',
    'create.placeholderContent': '请输入帖子内容（至少10个字符）',
    'create.placeholderTags': '用逗号分隔多个标签，例如：技术,编程,Python',
    'create.tagsHint': '标签之间用逗号分隔',
    'create.cancel': '取消',
    'create.submit': '发布',
    'create.submitting': '发布中...',
    'create.errorRequired': '请填写所有必填字段',
    'create.errorCategory': '请选择有效的版块',
    'create.errorSubmit': '发布失败，请检查输入信息',
    'create.errorValidationPrefix': '验证失败: ',
    'post.commentPlaceholder': '写下你的评论...',
    'post.commentSubmitting': '发布中...',
    'post.commentSubmit': '发布评论',
    'post.actionLike': '点赞',
    'post.actionUnlike': '取消点赞',
    'post.needLogin': '请先登录',
    'post.actionFailed': '操作失败，请重试',
    'post.imageAlt': '帖子图片',
    'post.loginToComment': '请',
    'post.loginLink': '登录',
    'post.loginSuffix': '后发表评论',
    'post.commentsTitle': '评论',
    'post.commentCountSuffix': '条评论',
    'post.viewSuffix': '次浏览',
    'comment.reply': '回复',
    'comment.likesSuffix': '点赞',
    'comment.replyPlaceholder': '写下你的回复...',
    'comment.cancel': '取消',
    'comment.submit': '发布回复',
    'comment.submitting': '发布中...',
    'comment.empty': '暂无评论',
    'comment.anonymous': '匿名用户',
    'comment.unknownTime': '未知时间',
    'profile.postsTitle': '发布的帖子',
    'profile.empty': '该用户还没有发布任何帖子',
    'profile.delete': '删除帖子',
    'profile.deleting': '删除中...',
    'image.label': '图片（可选）',
    'image.alertSelect': '请选择图片文件',
    'image.alertMax': '最多只能上传 {max} 张图片',
    'image.alertSize': '图片大小不能超过 5MB',
    'image.processFail': '处理图片失败，请重试',
    'image.uploadFail': '图片 {name} 上传失败: {message}',
    'image.uploading': '上传中...',
    'image.cta': '点击或拖拽图片到这里上传',
    'image.hint': '支持 JPEG、PNG、GIF、WebP，单张不超过 5MB，最多 {max} 张',
    'image.previewUploading': '上传中...',
    'image.previewError': '上传失败',
    'image.delete': '删除',
    'image.alt': '预览 {index}',
  },
  en: {
    'common.loading': 'Loading...',

    'header.searchPlaceholder': 'Search posts or users...',
    'header.toLight': 'Switch to light mode',
    'header.toDark': 'Switch to dark mode',
    'header.lightLabel': 'Light mode',
    'header.darkLabel': 'Dark mode',
    'header.create': 'Post',
    'header.createTitle': 'Create a new post',
    'header.userMenu': 'User menu',
    'header.profile': 'My profile',
    'header.logout': 'Logout',
    'header.login': 'Log in',
    'header.register': 'Sign up',
    'header.inbox': 'Notifications',
    'header.markAllRead': 'Mark all as read',
    'header.markAsRead': 'Mark as read',
    'header.noNotifications': 'No notifications',
    'sidebar.home': 'Home',
    'sidebar.about': 'About',
    'sidebar.contact': 'Contact',
    'sidebar.changelog': 'Changelog',
    'sidebar.fixes': 'Fixes',
    'right.categoriesTitle': 'Categories',
    'right.tagsTitle': 'Tags',
    'right.loading': 'Loading...',
    'right.emptyCategories': 'No categories yet',
    'right.emptyTags': 'No tags yet',
    'right.postsSuffix': 'posts',

    'home.latest': 'Latest',
    'home.hot': 'Hot',
    'home.loading': 'Loading...',
    'home.emptyTitle': 'No posts yet',
    'home.emptyDesc': 'No related posts found for now. Please try again later.',
    'home.loadMore': 'Load more',
    'search.title': 'Search results',
    'search.keywordPrefix': 'Keyword: ',
    'search.loading': 'Searching...',
    'search.enterKeyword': 'Please enter a search keyword',
    'search.noResultsTitle': 'No posts found',
    'search.noResultsDesc': 'No posts matched this keyword. Please try another one.',
    'search.resultsPrefix': 'Found ',
    'search.resultsSuffix': ' results',

    'auth.loginTitle': 'Log in',
    'auth.agreementPrefix': 'By continuing, you agree to our ',
    'auth.agreementUser': 'User Agreement',
    'auth.agreementPrivacyPrefix': ' and acknowledge the ',
    'auth.agreementPrivacy': 'Privacy Policy',
    'auth.emailOrUsername': 'Email or username *',
    'auth.emailOrUsernamePlaceholder': 'Email or username',
    'auth.password': 'Password *',
    'auth.passwordPlaceholder': 'Password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.loggingIn': 'Logging in...',
    'auth.login': 'Log in',
    'auth.newUser': 'New here?',
    'auth.register': 'Sign up',
    'create.title': 'Create a new post',
    'create.fieldTitle': 'Title *',
    'create.fieldCategory': 'Category *',
    'create.fieldContent': 'Content *',
    'create.fieldTags': 'Tags (optional)',
    'create.placeholderTitle': 'Enter a title (5-200 characters)',
    'create.placeholderContent': 'Enter post content (at least 10 characters)',
    'create.placeholderTags': 'Separate multiple tags with commas, e.g. tech,coding,Python',
    'create.tagsHint': 'Separate tags with commas',
    'create.cancel': 'Cancel',
    'create.submit': 'Post',
    'create.submitting': 'Posting...',
    'create.errorRequired': 'Please fill out all required fields',
    'create.errorCategory': 'Please select a valid category',
    'create.errorSubmit': 'Failed to post. Please check your input.',
    'create.errorValidationPrefix': 'Validation failed: ',
    'post.commentPlaceholder': 'Write your comment...',
    'post.commentSubmitting': 'Posting...',
    'post.commentSubmit': 'Post comment',
    'post.actionLike': 'Like',
    'post.actionUnlike': 'Unlike',
    'post.needLogin': 'Please log in first',
    'post.actionFailed': 'Action failed, please retry.',
    'post.imageAlt': 'Post image',
    'post.loginToComment': 'Please ',
    'post.loginLink': 'log in',
    'post.loginSuffix': ' to comment',
    'post.commentsTitle': 'Comments',
    'post.commentCountSuffix': ' comments',
    'post.viewSuffix': ' views',
    'comment.reply': 'Reply',
    'comment.likesSuffix': 'likes',
    'comment.replyPlaceholder': 'Write your reply...',
    'comment.cancel': 'Cancel',
    'comment.submit': 'Post reply',
    'comment.submitting': 'Posting...',
    'comment.empty': 'No comments yet',
    'comment.anonymous': 'Anonymous',
    'comment.unknownTime': 'Unknown time',
    'profile.postsTitle': 'Posts',
    'profile.empty': 'This user has not posted anything yet',
    'profile.delete': 'Delete post',
    'profile.deleting': 'Deleting...',
    'image.label': 'Images (optional)',
    'image.alertSelect': 'Please choose image files.',
    'image.alertMax': 'You can upload up to {max} images.',
    'image.alertSize': 'Each image must be smaller than 5 MB.',
    'image.processFail': 'Failed to process images. Please try again.',
    'image.uploadFail': 'Failed to upload {name}: {message}',
    'image.uploading': 'Uploading...',
    'image.cta': 'Click or drag images here to upload',
    'image.hint': 'Supports JPEG, PNG, GIF, WebP. Max 5 MB per file, up to {max} images.',
    'image.previewUploading': 'Uploading...',
    'image.previewError': 'Upload failed',
    'image.delete': 'Remove',
    'image.alt': 'Preview {index}',
  },
  ja: {
    'common.loading': '読み込み中...',

    'header.searchPlaceholder': '投稿やユーザーを検索...',
    'header.toLight': 'ライトモードに切り替え',
    'header.toDark': 'ダークモードに切り替え',
    'header.lightLabel': 'ライトモード',
    'header.darkLabel': 'ダークモード',
    'header.create': '投稿',
    'header.createTitle': '新しい投稿を作成',
    'header.userMenu': 'ユーザーメニュー',
    'header.profile': 'マイプロフィール',
    'header.logout': 'ログアウト',
    'header.login': 'ログイン',
    'header.register': '新規登録',
    'header.inbox': '通知',
    'header.markAllRead': 'すべて既読にする',
    'header.markAsRead': '既読にする',
    'header.noNotifications': '通知はありません',
    'sidebar.home': 'ホーム',
    'sidebar.about': '私たちについて',
    'sidebar.contact': 'お問い合わせ',
    'sidebar.changelog': '更新履歴',
    'sidebar.fixes': '修正情報',
    'right.categoriesTitle': 'カテゴリー',
    'right.tagsTitle': 'タグ',
    'right.loading': '読み込み中...',
    'right.emptyCategories': 'カテゴリーがありません',
    'right.emptyTags': 'タグがありません',
    'right.postsSuffix': '件',

    'home.latest': '最新',
    'home.hot': '人気',
    'home.loading': '読み込み中...',
    'home.emptyTitle': '投稿がありません',
    'home.emptyDesc': '関連する投稿はまだありません。しばらくしてからもう一度お試しください。',
    'home.loadMore': 'もっと見る',
    'search.title': '検索結果',
    'search.keywordPrefix': 'キーワード：',
    'search.loading': '検索中...',
    'search.enterKeyword': '検索キーワードを入力してください',
    'search.noResultsTitle': '該当する投稿が見つかりませんでした',
    'search.noResultsDesc': '別のキーワードでお試しください。',
    'search.resultsPrefix': '',
    'search.resultsSuffix': '件の結果が見つかりました',

    'auth.loginTitle': 'ログイン',
    'auth.agreementPrefix': '続行すると、',
    'auth.agreementUser': '利用規約',
    'auth.agreementPrivacyPrefix': 'および',
    'auth.agreementPrivacy': 'プライバシーポリシー',
    'auth.emailOrUsername': 'メールアドレスまたはユーザー名 *',
    'auth.emailOrUsernamePlaceholder': 'メールアドレスまたはユーザー名',
    'auth.password': 'パスワード *',
    'auth.passwordPlaceholder': 'パスワード',
    'auth.forgotPassword': 'パスワードをお忘れですか？',
    'auth.loggingIn': 'ログイン中...',
    'auth.login': 'ログイン',
    'auth.newUser': '初めての方は',
    'auth.register': '新規登録',
    'create.title': '新規投稿',
    'create.fieldTitle': 'タイトル *',
    'create.fieldCategory': 'カテゴリー *',
    'create.fieldContent': '内容 *',
    'create.fieldTags': 'タグ（任意）',
    'create.placeholderTitle': '5〜200文字でタイトルを入力してください',
    'create.placeholderContent': '少なくとも10文字の本文を入力してください',
    'create.placeholderTags': '例：テクノロジー,プログラミング,Python',
    'create.tagsHint': 'タグはカンマで区切ってください',
    'create.cancel': 'キャンセル',
    'create.submit': '投稿する',
    'create.submitting': '投稿中...',
    'create.errorRequired': '必須項目をすべて入力してください',
    'create.errorCategory': '有効なカテゴリーを選択してください',
    'create.errorSubmit': '投稿に失敗しました。入力内容をご確認ください。',
    'create.errorValidationPrefix': '検証エラー: ',
    'post.commentPlaceholder': 'コメントを入力してください...',
    'post.commentSubmitting': '投稿中...',
    'post.commentSubmit': 'コメントを投稿',
    'post.actionLike': 'いいね',
    'post.actionUnlike': 'いいねを取り消す',
    'post.needLogin': '先にログインしてください',
    'post.actionFailed': '操作に失敗しました。再試行してください。',
    'post.imageAlt': '投稿画像',
    'post.loginToComment': 'コメントするには',
    'post.loginLink': 'ログイン',
    'post.loginSuffix': 'してください',
    'post.commentsTitle': 'コメント',
    'post.commentCountSuffix': '件のコメント',
    'post.viewSuffix': '回の閲覧',
    'comment.reply': '返信',
    'comment.likesSuffix': '件のいいね',
    'comment.replyPlaceholder': '返信を入力してください...',
    'comment.cancel': 'キャンセル',
    'comment.submit': '返信を投稿',
    'comment.submitting': '投稿中...',
    'comment.empty': 'コメントはまだありません',
    'comment.anonymous': '匿名ユーザー',
    'comment.unknownTime': '不明な時間',
    'profile.postsTitle': '投稿一覧',
    'profile.empty': 'このユーザーはまだ投稿していません',
    'profile.delete': '投稿を削除',
    'profile.deleting': '削除中...',
    'image.label': '画像（任意）',
    'image.alertSelect': '画像ファイルを選択してください。',
    'image.alertMax': 'アップロードできるのは最大 {max} 枚までです。',
    'image.alertSize': '各画像のサイズは 5MB 未満である必要があります。',
    'image.processFail': '画像の処理に失敗しました。もう一度お試しください。',
    'image.uploadFail': '{name} のアップロードに失敗しました: {message}',
    'image.uploading': 'アップロード中...',
    'image.cta': 'クリックまたはドラッグ＆ドロップで画像を追加',
    'image.hint': 'JPEG / PNG / GIF / WebP 対応、1枚 5MB 以内、最大 {max} 枚まで',
    'image.previewUploading': 'アップロード中...',
    'image.previewError': 'アップロード失敗',
    'image.delete': '削除',
    'image.alt': 'プレビュー {index}',
  },
}

const LanguageContext = createContext({
  language: 'zh',
  setLanguage: () => {},
  t: (key) => key,
})

const getInitialLanguage = () => {
  if (typeof window === 'undefined') return 'zh'
  return localStorage.getItem(STORAGE_KEY) || 'zh'
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(getInitialLanguage)

  useEffect(() => {
    if (typeof window === 'undefined') return
    localStorage.setItem(STORAGE_KEY, language)
  }, [language])

  const t = (key) => {
    const dict = translations[language] || translations.zh
    return dict[key] || translations.zh[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)



