import React, { createContext, useContext, useEffect, useState } from 'react'

const STORAGE_KEY = 'app-language'

const translations = {
  zh: {
    'common.ok': '确定',

    'common.loading': '加载中...',

    'header.searchPlaceholder': '搜索',
    'header.toLight': '切换到日间模式',
    'header.toDark': '切换到夜间模式',
    'header.lightLabel': '日间模式',
    'header.darkLabel': '夜间模式',
    'header.create': '发布',
    'header.createTitle': '发布新帖子',
    'header.userMenu': '用户菜单',
    'header.profile': '我的资料',
    'header.logout': '登出',
    'header.login': '登录',
    'header.register': '注册',
    'header.inbox': '通知',
    'header.markAllRead': '全部已读',
    'header.markAsRead': '标记为已读',
    'header.noNotifications': '暂无通知',
    'header.actionsTitle': '快速操作',
    'header.actionsTools': '工具与切换',
    'header.actionsPrimary': '发布与账户',
    'header.actionsAll': '快速功能',
    'header.languageTitle': '选择语言',
    'header.themeColorTitle': '主题颜色',
    'sidebar.home': '首页',
    'sidebar.about': '关于我们',
    'sidebar.contact': '联系我们',
    'sidebar.privacy': '隐私政策',
    'sidebar.terms': '用户协议',
    'sidebar.policies': '合规与政策',
    'sidebar.changelog': '更新日志',
    'sidebar.fixes': '问题修复',
    'sidebar.navToggle': '首页菜单',
    'right.categoriesTitle': '版块分类',
    'right.tagsTitle': '标签',
    'right.loading': '加载中...',
    'right.emptyCategories': '暂无版块',
    'right.emptyTags': '暂无标签',
    'right.postsSuffix': '帖子',
    'right.containerFullHint': '装满会发生什么',

    // 分类名称翻译
    'category.技术讨论': '技术讨论',
    'category.问答求助': '问答求助',
    'category.资源分享': '资源分享',
    'category.闲聊灌水': '闲聊灌水',
    'category.项目展示': '项目展示',

    'home.latest': '最新',
    'home.hot': '热门',
    'home.loading': '加载中...',
    'home.emptyTitle': '暂无帖子',
    'home.emptyDesc': '暂时没有找到相关帖子，请稍后再试',
    'home.loadMore': '加载更多',
    'home.viewByDate': '按日期查看',
    'home.today': '今天',
    'home.yesterday': '昨天',
    'home.viewingDate': '正在查看：{date} 的帖子',
    'home.clearFilter': '清除筛选',
    'home.postsCount': '{count} 条',
    'home.expandMonth': '展开月视图',
    'home.collapseWeek': '收起为周视图',
    'search.title': '搜索结果',
    'search.keywordPrefix': '关键词：',
    'search.loading': '搜索中...',
    'search.enterKeyword': '请输入搜索关键词',
    'search.noResultsTitle': '未找到相关帖子',
    'search.noResultsDesc': '没有找到包含该关键词的帖子，请尝试其他关键词',
    'search.resultsPrefix': '找到',
    'search.resultsSuffix': '个结果',

    'auth.loginTitle': '登录',
    'auth.agreementPrefix': '继续操作即表示您同意我们的',
    'auth.agreementUser': '用户协议',
    'auth.agreementPrivacyPrefix': '并确认您了解',
    'auth.agreementPrivacy': '隐私政策',
    'auth.emailOrUsername': '邮箱或用户名 *',
    'auth.emailOrUsernamePlaceholder': '邮箱或用户名',
    'auth.password': '密码 *',
    'auth.passwordPlaceholder': '密码',
    'auth.forgotPassword': '忘记密码？',
    'auth.loggingIn': '登录中...',
    'auth.login': '登录',
    'auth.newUser': '新用户？',
    'auth.register': '注册',
    'auth.registering': '注册中...',
    'auth.username': '用户名 *',
    'auth.usernamePlaceholder': '3-20个字符，仅字母、数字和下划线',
    'auth.email': '邮箱 *',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.verificationCode': '验证码 *',
    'auth.verificationCodePlaceholder': '请输入6位验证码',
    'auth.sendCode': '获取验证码',
    'auth.sendingCode': '发送中...',
    'auth.codeSent': '验证码已发送到您的邮箱，有效期5分钟',
    'auth.retryAfter': '{countdown}秒后重试',
    'auth.confirmPassword': '确认密码 *',
    'auth.confirmPasswordPlaceholder': '再次输入密码',
    'auth.passwordPlaceholder': '至少6个字符',
    'auth.hasAccount': '已有账户？',
    'auth.consentLabel': '我已阅读并同意《用户协议》和《隐私政策》',
    'auth.termsTitle': '用户协议',
    'auth.privacyTitle': '隐私政策',
    'auth.agreementModalHint': '以下为概要说明，完整内容请查看文档。',
    'auth.openFull': '查看完整内容',
    'auth.termsSummary': '本用户协议说明您的账户、行为规范、内容发布和责任。继续使用即表示接受全部条款。',
    'auth.privacySummary': '本隐私政策说明我们如何收集、使用和保护您的个人信息。',
    'auth.error.consentRequired': '请先勾选同意用户协议和隐私政策',
    'auth.error.emailRequired': '请先输入邮箱地址',
    'auth.error.invalidEmail': '请输入有效的邮箱地址',
    'auth.error.sendCodeFailed': '发送验证码失败，请稍后重试',
    'auth.error.codeRequired': '请输入验证码',
    'auth.error.passwordMismatch': '两次输入的密码不一致',
    'auth.error.passwordTooShort': '密码长度至少为6位',
    'auth.error.codeNotSent': '请先获取验证码',
    'create.title': '发布新帖子',
    'create.fieldTitle': '标题 *',
    'create.fieldCategory': '版块 *',
    'create.fieldContent': '内容 *',
    'create.fieldTags': '标签（可选）',
    'create.placeholderTitle': '请输入帖子标题（5-200个字符）',
    'create.placeholderContent': '请输入帖子内容（至少10个字符）',
    'create.placeholderTags': '用逗号分隔多个标签，例如：技术,编程,Python',
    'create.tagsHint': '标签之间用逗号分隔',
    'create.cancel': '取消',
    'create.submit': '发布',
    'create.submitting': '发布中...',
    'create.errorRequired': '请填写所有必填字段',
    'create.errorCategory': '请选择有效的版块',
    'create.errorSubmit': '发布失败，请检查输入信息',
    'create.errorValidationPrefix': '验证失败: ',
    'post.commentPlaceholder': '写下你的评论...',
    'post.commentSubmitting': '发布中...',
    'post.commentSubmit': '发布评论',
    'post.actionLike': '点赞',
    'post.actionUnlike': '取消点赞',
    'post.needLogin': '请先登录',
    'post.actionFailed': '操作失败，请重试',
    'post.imageAlt': '帖子图片',
    'post.loginToComment': '请',
    'post.loginLink': '登录',
    'post.loginSuffix': '后发表评论',
    'post.commentsTitle': '评论',
    'post.commentCountSuffix': '条评论',
    'post.viewSuffix': '次浏览',
    'comment.reply': '回复',
    'comment.likesSuffix': '点赞',
    'comment.replyPlaceholder': '写下你的回复...',
    'comment.cancel': '取消',
    'comment.submit': '发布回复',
    'comment.submitting': '发布中...',
    'comment.empty': '暂无评论',
    'comment.anonymous': '匿名用户',
    'comment.unknownTime': '未知时间',
    'profile.postsTitle': '发布的帖子',
    'profile.empty': '该用户还没有发布任何帖子',
    'profile.delete': '删除帖子',
    'profile.deleting': '删除中...',
    'profile.posts': '帖子',
    'profile.comments': '评论',
    'profile.likes': '获赞',
    'profile.level': '等级',
    'profile.joinTime': '加入时间',
    'profile.stats': '用户数据',
    'profile.loading': '加载中...',
    'profile.exp': '经验',
    'profile.expToNext': '经验值到下一级',
    'profile.toNextLevel': '到下一级',
    'profile.maxLevel': '已满级',
    'tasks.title': '每日任务',
    'tasks.post': '发布帖子',
    'tasks.like': '点赞帖子',
    'tasks.comment': '评论帖子',
    'tasks.completed': '已完成',
    'tasks.exp': '经验',
    'tasks.allCompleted': '🎉 今日任务全部完成！',
    'profile.userNotFound': '用户不存在',
    'profile.deleteConfirm': '确定要删除这条帖子吗？此操作无法撤销。',
    'profile.deleteFailed': '删除帖子失败，请重试',
    'profile.edit.title': '编辑资料',
    'profile.edit.button': '编辑资料',
    'profile.edit.avatar': '头像',
    'profile.edit.uploadAvatar': '上传头像',
    'profile.edit.changeAvatar': '更换头像',
    'profile.edit.removeAvatar': '移除头像',
    'profile.edit.avatarHint': '支持 JPG、PNG、GIF 格式，最大 2MB',
    'profile.edit.avatarInvalidType': '请选择图片文件',
    'profile.edit.avatarTooLarge': '头像大小不能超过 2MB',
    'profile.edit.uploading': '上传中...',
    'profile.edit.username': '用户名',
    'profile.edit.usernamePlaceholder': '3-20个字符，仅字母、数字和下划线',
    'profile.edit.usernameLimit': '用户名只能每30天修改一次，还需等待 {days} 天',
    'profile.edit.tag': '称号',
    'profile.edit.tagPlaceholder': '输入你的称号（最多20字）',
    'profile.edit.tagLimit': '称号只能每30天修改一次，还需等待 {days} 天',
    'tag.official': '官方',
    'profile.edit.bio': '个人简介',
    'profile.edit.bioPlaceholder': '介绍一下你自己吧...（最多200字）',
    'profile.edit.save': '保存',
    'profile.edit.saving': '保存中...',
    'profile.edit.cancel': '取消',
    'profile.edit.uploadFailed': '头像上传失败，请重试',
    'profile.edit.updateFailed': '更新资料失败，请重试',
    'image.label': '图片（可选）',
    'image.alertSelect': '请选择图片文件',
    'image.alertMax': '最多只能上传 {max} 张图片',
    'image.alertSize': '图片大小不能超过 5MB',
    'image.processFail': '处理图片失败，请重试',
    'image.uploadFail': '图片 {name} 上传失败: {message}',
    'image.uploading': '上传中...',
    'image.cta': '点击或拖拽图片到这里上传',
    'image.hint': '支持 JPEG、PNG、GIF、WebP，单张不超过 5MB，最多 {max} 张',
    'image.previewUploading': '上传中...',
    'image.previewError': '上传失败',
    'image.delete': '删除',
    'image.alt': '预览 {index}',
    'cookie.title': 'Cookie 使用提示',
    'cookie.description': '我们使用 Cookie 来改善您的浏览体验、分析网站流量并个性化内容。继续使用本网站即表示您同意我们的 Cookie 政策。了解更多信息，请查看我们的',
    'cookie.privacyLink': '隐私政策',
    'cookie.accept': '接受',
    'cookie.decline': '拒绝',
    'age.title': '年龄验证',
    'age.bannerTitle': '此网站适用于 18 岁及以上用户',
    'age.bannerDescription': '根据相关法律法规，本网站仅面向年满 18 周岁的用户提供服务。继续使用本网站即表示您确认已年满 18 岁，并同意遵守我们的用户协议和隐私政策。',
    'age.bannerNote': '如果您未满 18 岁，请选择"我没满 18 岁"选项。我们建议未成年人在家长或监护人的指导下使用互联网。',
    'age.bannerAccept': '我已年满 18 岁',
    'age.bannerDecline': '我没满 18 岁',

    // PWA 安装提示
    'pwa.installTitle': '安装 REForum',
    'pwa.installDescription': '将 REForum 添加到主屏幕，获得更好的使用体验',
    'pwa.installButton': '安装',
    'pwa.dismissButton': '稍后',

    // 错误提示
    'error.loadFailed': '加载失败',
    'error.detail': '详情:',
    'error.retry': '重试',
    'error.networkHint': '提示：请确保后端服务正在运行',
    'error.checkSteps': '检查步骤：',
    'error.checkStep1': '确认后端服务已启动（通常在 http://localhost:3000）',
    'error.checkStep2': '检查浏览器控制台的网络请求错误',
    'error.checkStep3': '查看后端日志是否有错误信息',
    'error.serverError': '服务器错误，可能是数据库连接问题',
    'error.cannotConnect': '无法连接到服务器，请检查后端服务是否运行',
    'error.loadPostsFailed': '加载帖子失败',
    'error.serverInternalError': '服务器内部错误',
    'error.occurred': '出现错误',
    'error.pageLoadError': '页面加载时出现错误',
    'error.refreshPage': '刷新页面',
    'error.loginFailed': '登录失败，请检查用户名和密码',
    'error.registerFailed': '注册失败，请检查输入信息',
    'error.rateLimit': '请求过于频繁，请 {retryAfter} 秒后再试',

    // 通知消息
    'notification.newPost': '{username} 发布了新帖子',

    'age.description': '根据相关法律法规，您需要确认您已年满 18 岁才能访问本网站。',
    'age.birthDate': '出生日期',
    'age.year': '年份',
    'age.month': '月份',
    'age.day': '日期',
    'age.verify': '验证',
    'age.exit': '退出',
    'age.error.required': '请填写完整的出生日期',
    'age.error.invalid': '请输入有效的日期',
    'age.error.underage': '抱歉，您必须年满 18 岁才能访问本网站',
  },
  en: {
    'common.ok': 'OK',

    'common.loading': 'Loading...',

    'header.searchPlaceholder': 'Search',
    'header.toLight': 'Switch to light mode',
    'header.toDark': 'Switch to dark mode',
    'header.lightLabel': 'Light mode',
    'header.darkLabel': 'Dark mode',
    'header.create': 'Post',
    'header.createTitle': 'Create a new post',
    'header.userMenu': 'User menu',
    'header.profile': 'My profile',
    'header.logout': 'Logout',
    'header.login': 'Log in',
    'header.register': 'Sign up',
    'header.inbox': 'Notifications',
    'header.markAllRead': 'Mark all as read',
    'header.markAsRead': 'Mark as read',
    'header.noNotifications': 'No notifications',
    'header.actionsTitle': 'Quick actions',
    'header.actionsTools': 'Tools & toggles',
    'header.actionsPrimary': 'Primary actions',
    'header.actionsAll': 'All actions',
    'header.themeColorTitle': 'Theme color',
    'header.languageTitle': 'Choose language',
    'header.themeColorTitle': 'Theme color',
    'sidebar.home': 'Home',
    'sidebar.about': 'About',
    'sidebar.contact': 'Contact',
    'sidebar.privacy': 'Privacy Policy',
    'sidebar.terms': 'Terms of Service',
    'sidebar.policies': 'Compliance & Policies',
    'sidebar.changelog': 'Changelog',
    'sidebar.fixes': 'Fixes',
    'sidebar.navToggle': 'Menu',
    'right.categoriesTitle': 'Categories',
    'right.tagsTitle': 'Tags',
    'right.loading': 'Loading...',
    'right.emptyCategories': 'No categories yet',
    'right.emptyTags': 'No tags yet',
    'right.postsSuffix': 'posts',
    'right.containerFullHint': 'What happens when it\'s full?',

    // Category name translations
    'category.技术讨论': 'Tech Discussion',
    'category.问答求助': 'Q&A Help',
    'category.资源分享': 'Resource Sharing',
    'category.闲聊灌水': 'Casual Chat',
    'category.项目展示': 'Project Showcase',

    'home.latest': 'Latest',
    'home.hot': 'Hot',
    'home.loading': 'Loading...',
    'home.emptyTitle': 'No posts yet',
    'home.emptyDesc': 'No related posts found for now. Please try again later.',
    'home.loadMore': 'Load more',
    'home.viewByDate': 'View by Date',
    'home.today': 'Today',
    'home.yesterday': 'Yesterday',
    'home.viewingDate': 'Viewing posts from {date}',
    'home.clearFilter': 'Clear Filter',
    'home.postsCount': '{count} posts',
    'home.expandMonth': 'Expand to month view',
    'home.collapseWeek': 'Collapse to week view',
    'search.title': 'Search results',
    'search.keywordPrefix': 'Keyword: ',
    'search.loading': 'Searching...',
    'search.enterKeyword': 'Please enter a search keyword',
    'search.noResultsTitle': 'No posts found',
    'search.noResultsDesc': 'No posts matched this keyword. Please try another one.',
    'search.resultsPrefix': 'Found ',
    'search.resultsSuffix': ' results',

    'auth.loginTitle': 'Log in',
    'auth.agreementPrefix': 'By continuing, you agree to our ',
    'auth.agreementUser': 'User Agreement',
    'auth.agreementPrivacyPrefix': ' and acknowledge the ',
    'auth.agreementPrivacy': 'Privacy Policy',
    'auth.emailOrUsername': 'Email or username *',
    'auth.emailOrUsernamePlaceholder': 'Email or username',
    'auth.password': 'Password *',
    'auth.passwordPlaceholder': 'Password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.loggingIn': 'Logging in...',
    'auth.login': 'Log in',
    'auth.newUser': 'New here?',
    'auth.register': 'Sign up',
    'auth.registering': 'Registering...',
    'auth.username': 'Username *',
    'auth.usernamePlaceholder': '3-20 characters, letters, numbers and underscores only',
    'auth.email': 'Email *',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.verificationCode': 'Verification Code *',
    'auth.verificationCodePlaceholder': 'Enter 6-digit code',
    'auth.sendCode': 'Get Code',
    'auth.sendingCode': 'Sending...',
    'auth.codeSent': 'Code sent to your email, valid for 5 minutes',
    'auth.retryAfter': 'Retry in {countdown}s',
    'auth.confirmPassword': 'Confirm Password *',
    'auth.confirmPasswordPlaceholder': 'Re-enter password',
    'auth.passwordPlaceholder': 'At least 6 characters',
    'auth.hasAccount': 'Already have an account?',
    'auth.consentLabel': 'I have read and agree to the Terms and Privacy Policy',
    'auth.termsTitle': 'Terms of Service',
    'auth.privacyTitle': 'Privacy Policy',
    'auth.agreementModalHint': 'This is a brief summary. Please review the full documents.',
    'auth.openFull': 'View full content',
    'auth.termsSummary': 'These terms describe your account, conduct rules, content posting and responsibilities. Continuing means you accept all terms.',
    'auth.privacySummary': 'This policy explains how we collect, use, and protect your personal data.',
    'auth.error.consentRequired': 'Please check the box to agree to the terms and privacy policy first',
    'auth.error.emailRequired': 'Please enter your email address first',
    'auth.error.invalidEmail': 'Please enter a valid email address',
    'auth.error.sendCodeFailed': 'Failed to send verification code, please try again later',
    'auth.error.codeRequired': 'Please enter the verification code',
    'auth.error.passwordMismatch': 'Passwords do not match',
    'auth.error.passwordTooShort': 'Password must be at least 6 characters',
    'auth.error.codeNotSent': 'Please get the verification code first',
    'create.title': 'Create a new post',
    'create.fieldTitle': 'Title *',
    'create.fieldCategory': 'Category *',
    'create.fieldContent': 'Content *',
    'create.fieldTags': 'Tags (optional)',
    'create.placeholderTitle': 'Enter a title (5-200 characters)',
    'create.placeholderContent': 'Enter post content (at least 10 characters)',
    'create.placeholderTags': 'Separate multiple tags with commas, e.g. tech,coding,Python',
    'create.tagsHint': 'Separate tags with commas',
    'create.cancel': 'Cancel',
    'create.submit': 'Post',
    'create.submitting': 'Posting...',
    'create.errorRequired': 'Please fill out all required fields',
    'create.errorCategory': 'Please select a valid category',
    'create.errorSubmit': 'Failed to post. Please check your input.',
    'create.errorValidationPrefix': 'Validation failed: ',
    'post.commentPlaceholder': 'Write your comment...',
    'post.commentSubmitting': 'Posting...',
    'post.commentSubmit': 'Post comment',
    'post.actionLike': 'Like',
    'post.actionUnlike': 'Unlike',
    'post.needLogin': 'Please log in first',
    'post.actionFailed': 'Action failed, please retry.',
    'post.imageAlt': 'Post image',
    'post.loginToComment': 'Please ',
    'post.loginLink': 'log in',
    'post.loginSuffix': ' to comment',
    'post.commentsTitle': 'Comments',
    'post.commentCountSuffix': ' comments',
    'post.viewSuffix': ' views',
    'comment.reply': 'Reply',
    'comment.likesSuffix': 'likes',
    'comment.replyPlaceholder': 'Write your reply...',
    'comment.cancel': 'Cancel',
    'comment.submit': 'Post reply',
    'comment.submitting': 'Posting...',
    'comment.empty': 'No comments yet',
    'comment.anonymous': 'Anonymous',
    'comment.unknownTime': 'Unknown time',
    'profile.postsTitle': 'Posts',
    'profile.empty': 'This user has not posted anything yet',
    'profile.delete': 'Delete post',
    'profile.deleting': 'Deleting...',
    'profile.posts': 'Posts',
    'profile.comments': 'Comments',
    'profile.likes': 'Likes',
    'profile.level': 'Level',
    'profile.joinTime': 'Join Time',
    'profile.stats': 'User Data',
    'profile.loading': 'Loading...',
    'profile.userNotFound': 'User not found',
    'profile.exp': 'EXP',
    'profile.expToNext': 'EXP to next level',
    'profile.toNextLevel': 'to next level',
    'profile.maxLevel': 'Max Level',
    'tasks.title': 'Daily Tasks',
    'tasks.post': 'Post',
    'tasks.like': 'Like',
    'tasks.comment': 'Comment',
    'tasks.completed': 'Completed',
    'tasks.exp': 'EXP',
    'tasks.allCompleted': '🎉 All tasks completed today!',
    'profile.deleteConfirm': 'Are you sure you want to delete this post? This action cannot be undone.',
    'profile.deleteFailed': 'Failed to delete post, please try again',
    'profile.edit.title': 'Edit Profile',
    'profile.edit.button': 'Edit Profile',
    'profile.edit.avatar': 'Avatar',
    'profile.edit.uploadAvatar': 'Upload Avatar',
    'profile.edit.changeAvatar': 'Change Avatar',
    'profile.edit.removeAvatar': 'Remove Avatar',
    'profile.edit.avatarHint': 'Supports JPG, PNG, GIF. Max 2MB',
    'profile.edit.avatarInvalidType': 'Please select an image file',
    'profile.edit.avatarTooLarge': 'Avatar size must be less than 2MB',
    'profile.edit.uploading': 'Uploading...',
    'profile.edit.username': 'Username',
    'profile.edit.usernamePlaceholder': '3-20 characters, letters, numbers and underscores only',
    'profile.edit.usernameLimit': 'Username can only be changed once every 30 days. Please wait {days} more days.',
    'profile.edit.tag': 'Tag',
    'profile.edit.tagPlaceholder': 'Enter your tag (max 20 characters)',
    'profile.edit.tagLimit': 'Tag can only be changed once every 30 days. Please wait {days} more days.',
    'tag.official': 'Official',
    'profile.edit.bio': 'Bio',
    'profile.edit.bioPlaceholder': 'Tell us about yourself... (max 200 characters)',
    'profile.edit.save': 'Save',
    'profile.edit.saving': 'Saving...',
    'profile.edit.cancel': 'Cancel',
    'profile.edit.uploadFailed': 'Failed to upload avatar, please try again',
    'profile.edit.updateFailed': 'Failed to update profile, please try again',
    'image.label': 'Images (optional)',
    'image.alertSelect': 'Please choose image files.',
    'image.alertMax': 'You can upload up to {max} images.',
    'image.alertSize': 'Each image must be smaller than 5 MB.',
    'image.processFail': 'Failed to process images. Please try again.',
    'image.uploadFail': 'Failed to upload {name}: {message}',
    'image.uploading': 'Uploading...',
    'image.cta': 'Click or drag images here to upload',
    'image.hint': 'Supports JPEG, PNG, GIF, WebP. Max 5 MB per file, up to {max} images.',
    'image.previewUploading': 'Uploading...',
    'image.previewError': 'Upload failed',
    'image.delete': 'Remove',
    'image.alt': 'Preview {index}',
    'cookie.title': 'Cookie Notice',
    'cookie.description': 'We use cookies to enhance your browsing experience, analyze site traffic, and personalize content. By continuing to use this site, you consent to our use of cookies. To learn more, please see our',
    'cookie.privacyLink': 'Privacy Policy',
    'cookie.accept': 'Accept',
    'cookie.decline': 'Decline',
    'age.title': 'Age Verification',
    'age.bannerTitle': 'This site is for users aged 18 and over',
    'age.bannerDescription': 'In accordance with applicable laws and regulations, this website is intended for users who are 18 years of age or older. By continuing, you confirm that you are at least 18 years old and agree to comply with our Terms of Service and Privacy Policy.',
    'age.bannerNote': 'If you are under 18, please select "I am under 18". We recommend that minors use the internet under the guidance of parents or guardians.',
    'age.bannerAccept': 'I am 18 or older',
    'age.bannerDecline': 'I am under 18',

    // PWA Install Prompt
    'pwa.installTitle': 'Install REForum',
    'pwa.installDescription': 'Add REForum to your home screen for a better experience',
    'pwa.installButton': 'Install',
    'pwa.dismissButton': 'Later',

    // Error messages
    'error.loadFailed': 'Failed to load',
    'error.detail': 'Details:',
    'error.retry': 'Retry',
    'error.networkHint': '💡 Tip: Please ensure the backend service is running',
    'error.checkSteps': 'Check steps:',
    'error.checkStep1': '1. Confirm the backend service is started (usually at http://localhost:3000)',
    'error.checkStep2': '2. Check the network request errors in the browser console',
    'error.checkStep3': '3. Check the backend logs for error messages',
    'error.serverError': 'Server error, possibly a database connection issue',
    'error.cannotConnect': 'Cannot connect to server, please check if the backend service is running',
    'error.loadPostsFailed': 'Failed to load posts',
    'error.serverInternalError': 'Internal server error',
    'error.occurred': 'An error occurred',
    'error.pageLoadError': 'An error occurred while loading the page',
    'error.refreshPage': 'Refresh page',
    'error.loginFailed': 'Login failed, please check your username and password',
    'error.registerFailed': 'Registration failed, please check your input',
    'error.rateLimit': 'Too many requests, please try again in {retryAfter} seconds',

    // Notification messages
    'notification.newPost': '{username} posted a new post',

    'age.description': 'According to applicable laws and regulations, you must confirm that you are at least 18 years old to access this website.',
    'age.birthDate': 'Date of Birth',
    'age.year': 'Year',
    'age.month': 'Month',
    'age.day': 'Day',
    'age.verify': 'Verify',
    'age.exit': 'Exit',
    'age.error.required': 'Please enter your complete date of birth',
    'age.error.invalid': 'Please enter a valid date',
    'age.error.underage': 'Sorry, you must be at least 18 years old to access this website',
  },
  ja: {
    'common.ok': 'OK',

    'common.loading': '読み込み中...',

    'header.searchPlaceholder': '検索',
    'header.toLight': 'ライトモードに切り替え',
    'header.toDark': 'ダークモードに切り替え',
    'header.lightLabel': 'ライトモード',
    'header.darkLabel': 'ダークモード',
    'header.create': '投稿',
    'header.createTitle': '新しい投稿を作成',
    'header.userMenu': 'ユーザーメニュー',
    'header.profile': 'マイプロフィール',
    'header.logout': 'ログアウト',
    'header.login': 'ログイン',
    'header.register': '新規登録',
    'header.inbox': '通知',
    'header.markAllRead': 'すべて既読にする',
    'header.markAsRead': '既読にする',
    'header.noNotifications': '通知はありません',
    'header.actionsTitle': 'クイック操作',
    'header.actionsTools': 'ツールと切り替え',
    'header.actionsPrimary': '主要アクション',
    'header.actionsAll': 'すべての操作',
    'header.themeColorTitle': 'テーマカラー',
    'header.languageTitle': '言語を選択',
    'header.themeColorTitle': 'テーマカラー',
    'sidebar.home': 'ホーム',
    'sidebar.about': '私たちについて',
    'sidebar.contact': 'お問い合わせ',
    'sidebar.privacy': 'プライバシーポリシー',
    'sidebar.terms': '利用規約',
    'sidebar.policies': 'コンプライアンス・ポリシー',
    'sidebar.changelog': '更新履歴',
    'sidebar.fixes': '修正情報',
    'sidebar.navToggle': 'メニュー',
    'right.categoriesTitle': 'カテゴリー',
    'right.tagsTitle': 'タグ',
    'right.loading': '読み込み中...',
    'right.emptyCategories': 'カテゴリーがありません',
    'right.emptyTags': 'タグがありません',
    'right.postsSuffix': '件',
    'right.containerFullHint': '満杯になったらどうなる？',

    // カテゴリー名の翻訳
    'category.技术讨论': '技術討論',
    'category.问答求助': '質問・ヘルプ',
    'category.资源分享': 'リソース共有',
    'category.闲聊灌水': '雑談',
    'category.项目展示': 'プロジェクト展示',

    'home.latest': '最新',
    'home.hot': '人気',
    'home.loading': '読み込み中...',
    'home.emptyTitle': '投稿がありません',
    'home.emptyDesc': '関連する投稿はまだありません。しばらくしてからもう一度お試しください。',
    'home.loadMore': 'もっと見る',
    'home.viewByDate': '日付で表示',
    'home.today': '今日',
    'home.yesterday': '昨日',
    'home.viewingDate': '{date} の投稿を表示中',
    'home.clearFilter': 'フィルターをクリア',
    'home.postsCount': '{count} 件',
    'home.expandMonth': '月表示に展開',
    'home.collapseWeek': '週表示に折りたたむ',
    'search.title': '検索結果',
    'search.keywordPrefix': 'キーワード：',
    'search.loading': '検索中...',
    'search.enterKeyword': '検索キーワードを入力してください',
    'search.noResultsTitle': '該当する投稿が見つかりませんでした',
    'search.noResultsDesc': '別のキーワードでお試しください。',
    'search.resultsPrefix': '',
    'search.resultsSuffix': '件の結果が見つかりました',

    'auth.loginTitle': 'ログイン',
    'auth.agreementPrefix': '続行すると、',
    'auth.agreementUser': '利用規約',
    'auth.agreementPrivacyPrefix': 'および',
    'auth.agreementPrivacy': 'プライバシーポリシー',
    'auth.emailOrUsername': 'メールアドレスまたはユーザー名 *',
    'auth.emailOrUsernamePlaceholder': 'メールアドレスまたはユーザー名',
    'auth.password': 'パスワード *',
    'auth.passwordPlaceholder': 'パスワード',
    'auth.forgotPassword': 'パスワードをお忘れですか？',
    'auth.loggingIn': 'ログイン中...',
    'auth.login': 'ログイン',
    'auth.newUser': '初めての方は',
    'auth.register': '新規登録',
    'auth.registering': '登録中...',
    'auth.username': 'ユーザー名 *',
    'auth.usernamePlaceholder': '3-20文字、英数字とアンダースコアのみ',
    'auth.email': 'メールアドレス *',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.verificationCode': '確認コード *',
    'auth.verificationCodePlaceholder': '6桁のコードを入力',
    'auth.sendCode': 'コードを取得',
    'auth.sendingCode': '送信中...',
    'auth.codeSent': 'メールに送信されました。有効期限は5分です',
    'auth.retryAfter': '{countdown}秒後に再試行',
    'auth.confirmPassword': 'パスワード確認 *',
    'auth.confirmPasswordPlaceholder': 'パスワードを再入力',
    'auth.passwordPlaceholder': '少なくとも6文字',
    'auth.hasAccount': '既にアカウントをお持ちですか？',
    'auth.consentLabel': '利用規約とプライバシーポリシーに同意します',
    'auth.termsTitle': '利用規約',
    'auth.privacyTitle': 'プライバシーポリシー',
    'auth.agreementModalHint': '以下は概要です。必ず全文をご確認ください。',
    'auth.openFull': '全文を見る',
    'auth.termsSummary': '本規約はアカウント、行動規範、投稿内容、責任について定めています。続行することで全てに同意したとみなされます。',
    'auth.privacySummary': '本ポリシーは個人情報の収集・利用・保護について説明します。',
    'auth.error.consentRequired': '利用規約とプライバシーポリシーへの同意が必要です',
    'auth.error.emailRequired': 'まずメールアドレスを入力してください',
    'auth.error.invalidEmail': '有効なメールアドレスを入力してください',
    'auth.error.sendCodeFailed': '確認コードの送信に失敗しました。しばらくしてから再試行してください',
    'auth.error.codeRequired': '確認コードを入力してください',
    'auth.error.passwordMismatch': 'パスワードが一致しません',
    'auth.error.passwordTooShort': 'パスワードは少なくとも6文字である必要があります',
    'auth.error.codeNotSent': 'まず確認コードを取得してください',
    'create.title': '新規投稿',
    'create.fieldTitle': 'タイトル *',
    'create.fieldCategory': 'カテゴリー *',
    'create.fieldContent': '内容 *',
    'create.fieldTags': 'タグ（任意）',
    'create.placeholderTitle': '5〜200文字でタイトルを入力してください',
    'create.placeholderContent': '少なくとも10文字の本文を入力してください',
    'create.placeholderTags': '例：テクノロジー,プログラミング,Python',
    'create.tagsHint': 'タグはカンマで区切ってください',
    'create.cancel': 'キャンセル',
    'create.submit': '投稿する',
    'create.submitting': '投稿中...',
    'create.errorRequired': '必須項目をすべて入力してください',
    'create.errorCategory': '有効なカテゴリーを選択してください',
    'create.errorSubmit': '投稿に失敗しました。入力内容をご確認ください。',
    'create.errorValidationPrefix': '検証エラー: ',
    'post.commentPlaceholder': 'コメントを入力してください...',
    'post.commentSubmitting': '投稿中...',
    'post.commentSubmit': 'コメントを投稿',
    'post.actionLike': 'いいね',
    'post.actionUnlike': 'いいねを取り消す',
    'post.needLogin': '先にログインしてください',
    'post.actionFailed': '操作に失敗しました。再試行してください。',
    'post.imageAlt': '投稿画像',
    'post.loginToComment': 'コメントするには',
    'post.loginLink': 'ログイン',
    'post.loginSuffix': 'してください',
    'post.commentsTitle': 'コメント',
    'post.commentCountSuffix': '件のコメント',
    'post.viewSuffix': '回の閲覧',
    'comment.reply': '返信',
    'comment.likesSuffix': '件のいいね',
    'comment.replyPlaceholder': '返信を入力してください...',
    'comment.cancel': 'キャンセル',
    'comment.submit': '返信を投稿',
    'comment.submitting': '投稿中...',
    'comment.empty': 'コメントはまだありません',
    'comment.anonymous': '匿名ユーザー',
    'comment.unknownTime': '不明な時間',
    'profile.postsTitle': '投稿一覧',
    'profile.empty': 'このユーザーはまだ投稿していません',
    'profile.delete': '投稿を削除',
    'profile.deleting': '削除中...',
    'profile.posts': '投稿',
    'profile.comments': 'コメント',
    'profile.likes': 'いいね',
    'profile.level': 'レベル',
    'profile.joinTime': '参加日時',
    'profile.stats': 'ユーザーデータ',
    'profile.loading': '読み込み中...',
    'profile.userNotFound': 'ユーザーが見つかりません',
    'profile.exp': '経験値',
    'profile.expToNext': '次のレベルまでの経験値',
    'profile.toNextLevel': '次のレベルまで',
    'profile.maxLevel': '最大レベル',
    'tasks.title': 'デイリータスク',
    'tasks.post': '投稿',
    'tasks.like': 'いいね',
    'tasks.comment': 'コメント',
    'tasks.completed': '完了',
    'tasks.exp': '経験値',
    'tasks.allCompleted': '🎉 今日のタスクがすべて完了しました！',
    'profile.deleteConfirm': 'この投稿を削除してもよろしいですか？この操作は取り消せません。',
    'profile.deleteFailed': '投稿の削除に失敗しました。もう一度お試しください',
    'profile.edit.title': 'プロフィール編集',
    'profile.edit.button': 'プロフィール編集',
    'profile.edit.avatar': 'アバター',
    'profile.edit.uploadAvatar': 'アバターをアップロード',
    'profile.edit.changeAvatar': 'アバターを変更',
    'profile.edit.removeAvatar': 'アバターを削除',
    'profile.edit.avatarHint': 'JPG、PNG、GIF形式をサポート。最大2MB',
    'profile.edit.avatarInvalidType': '画像ファイルを選択してください',
    'profile.edit.avatarTooLarge': 'アバターサイズは2MB以下である必要があります',
    'profile.edit.uploading': 'アップロード中...',
    'profile.edit.username': 'ユーザー名',
    'profile.edit.usernamePlaceholder': '3-20文字、英数字とアンダースコアのみ',
    'profile.edit.usernameLimit': 'ユーザー名は30日に1回のみ変更可能です。あと {days} 日お待ちください。',
    'profile.edit.tag': 'タグ',
    'profile.edit.tagPlaceholder': 'タグを入力してください（最大20文字）',
    'profile.edit.tagLimit': 'タグは30日に1回のみ変更可能です。あと {days} 日お待ちください。',
    'tag.official': '公式',
    'profile.edit.bio': '自己紹介',
    'profile.edit.bioPlaceholder': '自己紹介を入力してください...（最大200文字）',
    'profile.edit.save': '保存',
    'profile.edit.saving': '保存中...',
    'profile.edit.cancel': 'キャンセル',
    'profile.edit.uploadFailed': 'アバターのアップロードに失敗しました。もう一度お試しください',
    'profile.edit.updateFailed': 'プロフィールの更新に失敗しました。もう一度お試しください',
    'image.label': '画像（任意）',
    'image.alertSelect': '画像ファイルを選択してください。',
    'image.alertMax': 'アップロードできるのは最大 {max} 枚までです。',
    'image.alertSize': '各画像のサイズは 5MB 未満である必要があります。',
    'image.processFail': '画像の処理に失敗しました。もう一度お試しください。',
    'image.uploadFail': '{name} のアップロードに失敗しました: {message}',
    'image.uploading': 'アップロード中...',
    'image.cta': 'クリックまたはドラッグ＆ドロップで画像を追加',
    'image.hint': 'JPEG / PNG / GIF / WebP 対応、1枚 5MB 以内、最大 {max} 枚まで',
    'image.previewUploading': 'アップロード中...',
    'image.previewError': 'アップロード失敗',
    'image.delete': '削除',
    'image.alt': 'プレビュー {index}',
    'cookie.title': 'Cookie 使用について',
    'cookie.description': '当サイトでは、閲覧体験の向上、サイトトラフィックの分析、コンテンツのパーソナライズのために Cookie を使用しています。サイトを引き続きご利用いただくことで、Cookie の使用に同意したものとみなされます。詳細については、',
    'cookie.privacyLink': 'プライバシーポリシー',
    'cookie.accept': '同意する',
    'cookie.decline': '拒否する',
    'age.bannerTitle': '本サイトは18歳以上の方を対象としています',
    'age.bannerDescription': '関連する法律・規制に基づき、本サイトは18歳以上のユーザーを対象としています。続行することで、18歳以上であることを確認し、利用規約およびプライバシーポリシーに同意したものとみなされます。',
    'age.bannerNote': '18歳未満の場合は、「18歳未満です」を選択してください。未成年者は保護者または後見人の指導のもとでインターネットを利用することをお勧めします。',
    'age.bannerAccept': '18歳以上です',
    'age.bannerDecline': '18歳未満です',

    // PWA インストールプロンプト
    'pwa.installTitle': 'REForum をインストール',
    'pwa.installDescription': 'ホーム画面に REForum を追加して、より良い体験を得ましょう',
    'pwa.installButton': 'インストール',
    'pwa.dismissButton': '後で',

    // エラーメッセージ
    'error.loadFailed': '読み込み失敗',
    'error.detail': '詳細:',
    'error.retry': '再試行',
    'error.networkHint': '💡 ヒント：バックエンドサービスが実行されていることを確認してください',
    'error.checkSteps': '確認手順：',
    'error.checkStep1': '1. バックエンドサービスが起動していることを確認（通常は http://localhost:3000）',
    'error.checkStep2': '2. ブラウザのコンソールでネットワークリクエストエラーを確認',
    'error.checkStep3': '3. バックエンドログにエラーメッセージがないか確認',
    'error.serverError': 'サーバーエラー、データベース接続の問題の可能性があります',
    'error.cannotConnect': 'サーバーに接続できません。バックエンドサービスが実行されているか確認してください',
    'error.loadPostsFailed': '投稿の読み込みに失敗しました',
    'error.serverInternalError': 'サーバー内部エラー',
    'error.occurred': 'エラーが発生しました',
    'error.pageLoadError': 'ページの読み込み中にエラーが発生しました',
    'error.refreshPage': 'ページを更新',
    'error.loginFailed': 'ログインに失敗しました。ユーザー名とパスワードを確認してください',
    'error.registerFailed': '登録に失敗しました。入力内容を確認してください',
    'error.rateLimit': 'リクエストが多すぎます。{retryAfter} 秒後にもう一度お試しください',

    // 通知メッセージ
    'notification.newPost': '{username} が新しい投稿をしました',

    'age.title': '年齢確認',
    'age.description': '関連する法律および規制に基づき、本サイトにアクセスするには 18 歳以上であることを確認する必要があります。',
    'age.birthDate': '生年月日',
    'age.year': '年',
    'age.month': '月',
    'age.day': '日',
    'age.verify': '確認',
    'age.exit': '終了',
    'age.error.required': '生年月日をすべて入力してください',
    'age.error.invalid': '有効な日付を入力してください',
    'age.error.underage': '申し訳ございませんが、本サイトにアクセスするには 18 歳以上である必要があります',
  },
}

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
})

const getInitialLanguage = () => {
  if (typeof window === 'undefined') return 'en'
  return localStorage.getItem(STORAGE_KEY) || 'en'
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(getInitialLanguage)

  useEffect(() => {
    if (typeof window === 'undefined') return
    localStorage.setItem(STORAGE_KEY, language)
  }, [language])

  const t = (key, params = {}) => {
    const dict = translations[language] || translations.en
    let text = dict[key] || translations.en[key] || key
    
    // 支持参数替换，例如 {countdown} 会被替换为实际值
    if (params && typeof text === 'string') {
      Object.keys(params).forEach(paramKey => {
        text = text.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), params[paramKey])
      })
    }
    
    return text
  }

  // 获取分类名称的翻译
  const getCategoryName = (categoryName) => {
    const key = `category.${categoryName}`
    const translated = t(key)
    // 如果翻译键不存在，返回原始名称
    return translated === key ? categoryName : translated
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getCategoryName }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)



